package com.ecommerce.auction_service;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalTime;

@Entity
@Table(name = "auction")
public class Auction {
    //should change to autogenerated PK in place of using catalog items id as auctions.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int auctionid;
    @Column(nullable = false, unique = true) //each auction entry corresponds to a single item; must be unique.
    private int auctioneditemid;
    @Column(nullable = false)
    private double startprice;
    @Column(nullable = false)
    private String auctiontype;
    @Column(nullable = false, columnDefinition = "DOUBLE default 0.00")
    private double highestbid;
    @Column(nullable = false, columnDefinition = "INT default 0")
    //this is default by 0 as user id can never be 0; implies noone has bid.
    private int highestbidderid;
    @Column(nullable = false)
    private LocalDate startdate;
    @Column(nullable = false)
    private LocalTime starttime;
    @Column(nullable = false)
    private LocalTime duration;
    @Column(nullable = false)
    private LocalTime endtime;
    @Column(nullable = false)
    private LocalDate enddate;
    private double decrementvalue;
    private LocalTime nextdecrementtime;
    private LocalDate nextdecrementdate;
    private LocalTime decrementinterval;

    public Auction() {
    }

    public Auction(int auctioneditemid, double startprice, String auctiontype, double highestbid, int highestbidderid, LocalDate startdate, LocalTime starttime, LocalTime duration, LocalTime endtime, LocalDate enddate, double decrementvalue, LocalTime nextdecrementtime, LocalDate nextdecrementdate, LocalTime decrementinterval) {
        this.auctioneditemid = auctioneditemid;
        this.startprice = startprice;
        this.auctiontype = auctiontype;
        this.highestbid = highestbid;
        this.highestbidderid = highestbidderid;
        this.startdate = startdate;
        this.starttime = starttime;
        this.duration = duration;
        this.endtime = endtime;
        this.enddate = enddate;
        this.decrementvalue = decrementvalue;
        this.nextdecrementtime = nextdecrementtime;
        this.nextdecrementdate = nextdecrementdate;
        this.decrementinterval = decrementinterval;
    }

    public int getAuctionid() {
        return auctionid;
    }

    public void setAuctionid(int auctionid) {
        this.auctionid = auctionid;
    }

    public int getAuctioneditemid() {
        return auctioneditemid;
    }

    public void setAuctioneditemid(int auctioneditemid) {
        this.auctioneditemid = auctioneditemid;
    }

    public double getStartprice() {
        return startprice;
    }

    public void setStartprice(double startprice) {
        this.startprice = startprice;
    }

    public String getAuctiontype() {
        return auctiontype;
    }

    public void setAuctiontype(String auctiontype) {
        this.auctiontype = auctiontype;
    }

    public double getHighestbid() {
        return highestbid;
    }

    public void setHighestbid(double highestbid) {
        this.highestbid = highestbid;
    }

    public int getHighestbidderid() {
        return highestbidderid;
    }

    public void setHighestbidderid(int highestbidderid) {
        this.highestbidderid = highestbidderid;
    }

    public LocalDate getStartdate() {
        return startdate;
    }

    public void setStartdate(LocalDate startdate) {
        this.startdate = startdate;
    }

    public LocalTime getStarttime() {
        return starttime;
    }

    public void setStarttime(LocalTime starttime) {
        this.starttime = starttime;
    }

    public LocalTime getDuration() {
        return duration;
    }

    public void setDuration(LocalTime duration) {
        this.duration = duration;
    }

    public LocalTime getEndtime() {
        return endtime;
    }

    public void setEndtime(LocalTime endtime) {
        this.endtime = endtime;
    }

    public LocalDate getEnddate() {
        return enddate;
    }

    public void setEnddate(LocalDate enddate) {
        this.enddate = enddate;
    }

    public double getDecrementvalue() {
        return decrementvalue;
    }

    public void setDecrementvalue(double decrementvalue) {
        this.decrementvalue = decrementvalue;
    }

    public LocalTime getNextdecrementtime() {
        return nextdecrementtime;
    }

    public void setNextdecrementtime(LocalTime nextdecrementtime) {
        this.nextdecrementtime = nextdecrementtime;
    }

    public LocalDate getNextdecrementdate() {
        return nextdecrementdate;
    }

    public void setNextdecrementdate(LocalDate nextdecrementdate) {
        this.nextdecrementdate = nextdecrementdate;
    }

    public LocalTime getDecrementinterval() {
        return decrementinterval;
    }

    public void setDecrementinterval(LocalTime decrementinterval) {
        this.decrementinterval = decrementinterval;
    }
}